import psycopg2
from psycopg2 import Error

class telemetry_database():

    host="localhost"
    database="postgres"
    user="postgres"
    password="Team6"

    def __init__(self):
        try:
            self.conn = psycopg2.connect(
                host = telemetry_database.host,
                database = telemetry_database.database,
                user = telemetry_database.user,
                password = telemetry_database.password
            )

            self.cursor = self.conn.cursor()
            self.conn.autocommit = True

            print("Connected to the database successfully!")

        except (Exception, Error) as e:
            print(f"Error connecting to the database: {e}")

    def __del__(self):
        try:
            self.conn.close()
            self.cursor.close()

            print("Successfully closed connection to the database.")

        except (Exception, Error) as e:
            print(f"Error closing the database: {e}")

    def create_telemetry_data_table(self, race, year):

        self.cursor.execute(f"""

        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE    table_name   = 'telemetry_{race}_{year}'
        );

        """)

        if self.cursor.fetchone()[0]:
            self.cursor.execute(f'DROP TABLE telemetry_{race}_{year} CASCADE;')

        self.cursor.execute(f"""
                            
        CREATE TABLE telemetry_{race}_{year} (
        tel_index           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        time                FLOAT NOT NULL,        -- seconds
        distance            FLOAT,                  -- meters
        rel_distance        FLOAT,                  -- meters (normalized)
        track_coordinate_x  FLOAT,
        track_coordinate_y  FLOAT,
        track_coordinate_z  FLOAT,
        rpm                 FLOAT,
        gear                INT CHECK (gear BETWEEN 0 AND 8),
        throttle            FLOAT CHECK (throttle BETWEEN 0 AND 100),
        brake               BOOLEAN,
        drs                 BOOLEAN,
        speed               FLOAT,                  -- km/h
        acc_x               FLOAT,                  -- m/s^2
        acc_y               FLOAT,                  -- m/s^2
        acc_z               FLOAT                   -- m/s^2
        );

        """)
    
    def remove_telemetry_table(self, race, year):

        print(f"Removing telemetry table for {race} {year}...")

        self.cursor.execute(f"""
            DROP TABLE telemetry_{race}_{year} CASCADE;
        """)

    def remove_metadata_table(self, race, year):

        print(f"Removing metadata table for {race} {year}...")

        self.cursor.execute(f"""
            DROP TABLE metadata_{race}_{year} CASCADE;
        """)

    def create_race_lap_data(self, race, year):
            
            self.cursor.execute(f"""

            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE    table_name   = 'metadata_{race}_{year}'
            );

            """)

            if self.cursor.fetchone()[0]:
                self.cursor.execute(f'DROP TABLE metadata_{race}_{year} CASCADE;')

            self.cursor.execute(f"""
                                
            CREATE TABLE metadata_{race}_{year} (
                lap_data_id INT PRIMARY KEY,
                driver_id   CHAR(3) NOT NULL,
                lap         INT NOT NULL,
                tel_index   INT NOT NULL,
                        
                CONSTRAINT fk_telemetry
                    FOREIGN KEY (tel_index)
                    REFERENCES telemetry_{race}_{year} (tel_index)
            );

            """)

    def clustering_results(self, cluster_method):
            
            self.cursor.execute(f"""

            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE    table_name   = 'clustering_results_{cluster_method}'
            );

            """)

            if self.cursor.fetchone()[0]:
                self.cursor.execute(f'DROP TABLE clustering_results_{cluster_method};')

            self.cursor.execute(f"""
                                
            CREATE TABLE clustering_results_{cluster_method} (
                index       INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                driver_id   CHAR(3) NOT NULL,
                year        INT NOT NULL,
                style_1     FLOAT CHECK (style_1 BETWEEN 0 AND 100)
            );

            """)

def main():
    db = telemetry_database()

    race_code_map = {"Belgian_Grand_Prix" : "BEL", "Chinese_Grand_Prix" : "CHN", "Hungarian_Grand_Prix" : "HUN", "Japanese_Grand_Prix" : "JPN", "Dutch_Grand_Prix" : "NED",
                    "Bahrain_Grand_Prix" : "BAH", "Italian_Grand_Prix" : "ITA", "Saudi_Arabian_Grand_Prix" : "SAU", "Azerbaijan_Grand_Prix" : "AZE", "Miami_Grand_Prix" : "MIA",
                    "Singapore_Grand_Prix" : "SIN", "Emilia_Romagna_Grand_Prix" : "EMI", "United_States_Grand_Prix" : "USA", "Monaco_Grand_Prix" : "MON", "Mexico_City_Grand_Prix" : "MEX",
                    "Spanish_Grand_Prix" : "ESP", "São_Paulo_Grand_Prix" : "SAO", "Las_Vegas_Grand_Prix" : "LAS", "Australian_Grand_Prix" : "AUS",
                    "Qatar_Grand_Prix" : "QAT", "British_Grand_Prix" : "GBR", "Abu_Dhabi_Grand_Prix" : "ABU", "Austrian_Grand_Prix": "AUT", "Canadian_Grand_Prix": "CAN"
                    }

    for race in race_code_map.keys():
        print(f"Creating tables for {race}...")
        db.create_telemetry_data_table(race_code_map[race], 2025)
        db.create_race_lap_data(race_code_map[race], 2025)

if __name__ == "__main__":
    main()
