import psycopg2
from psycopg2 import Error

class telemetry_database():

    host="localhost"
    database="postgres"
    user="postgres"
    password="Team6"

    def __init__(self):
        try:
            self.conn = psycopg2.connect(
                host = telemetry_database.host,
                database = telemetry_database.database,
                user = telemetry_database.user,
                password = telemetry_database.password
            )

            self.cursor = self.conn.cursor()
            self.conn.autocommit = True

            print("Connected to the database successfully!")

        except (Exception, Error) as e:
            print(f"Error connecting to the database: {e}")

    def __del__(self):
        try:
            self.conn.close()
            self.cursor.close()

            print("Successfully closed connection to the database.")

        except (Exception, Error) as e:
            print(f"Error closing the database: {e}")

    def create_telemetry_data_table(self):

        self.cursor.execute("""

        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE    table_name   = 'telemetry_data'
        );

        """)

        if self.cursor.fetchone()[0]:
            self.cursor.execute('DROP TABLE telemetry_data CASCADE;')

        self.cursor.execute("""
                            
        CREATE TABLE telemetry_data (
        tel_index           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        time                FLOAT NOT NULL,        -- seconds
        distance            FLOAT,                  -- meters
        rel_distance        FLOAT,                  -- meters (normalized)
        track_coordinate_x  FLOAT,
        track_coordinate_y  FLOAT,
        track_coordinate_z  FLOAT,
        rpm                 FLOAT,
        gear                INT CHECK (gear BETWEEN 0 AND 8),
        throttle            FLOAT CHECK (throttle BETWEEN 0 AND 100),
        brake               BOOLEAN,
        drs                 drs_status,
        speed               FLOAT,                  -- km/h
        acc_x               FLOAT,                  -- m/s^2
        acc_y               FLOAT,                  -- m/s^2
        acc_z               FLOAT                   -- m/s^2
        );

        """)

    def create_race_lap_data(self):
            
            self.cursor.execute("""

            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE    table_name   = 'race_lap_data'
            );

            """)

            if self.cursor.fetchone()[0]:
                self.cursor.execute('DROP TABLE race_lap_data CASCADE;')

            self.cursor.execute("""
                                
            CREATE TABLE race_lap_data (
                lap_data_id INT PRIMARY KEY,
                driver_id   CHAR(3) NOT NULL,
                lap         INT NOT NULL,
                race_name   CHAR(3) NOT NULL,
                year        INT NOT NULL,
                tel_index   INT NOT NULL,
                        
                CONSTRAINT fk_telemetry
                    FOREIGN KEY (tel_index)
                    REFERENCES telemetry_data (tel_index)
            );

            """)

    def clustering_results(self, cluster_method):
            
            self.cursor.execute(f"""

            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE    table_name   = 'clustering_results_{cluster_method}'
            );

            """)

            if self.cursor.fetchone()[0]:
                self.cursor.execute(f'DROP TABLE clustering_results_{cluster_method};')

            self.cursor.execute(f"""
                                
            CREATE TABLE clustering_results_{cluster_method} (
                index       INT PRIMARY KEY,
                driver_id   CHAR(3) NOT NULL,
                year        INT NOT NULL,
                style_1     FLOAT CHECK (style_1 BETWEEN 0 AND 100)
            );

            """)

    def query_driver_telemetry(self, race, driver):
        self.cursor.execute("SELECT * FROM race_lap_data;")

        # 4. Fetch all the results
        records = self.cursor.fetchall()

        # 5. Print the records
        print("Selected rows:")
        for row in records:
            print(row) # Each row is a tuple

def main():
    db = telemetry_database()

    ## METHODS FOR INITIAL TABLE CREATION
    # cluster_methods = ['kmeans', 'dbscan', 'fuzzyc', 'gaussian', 'hierarchical']

    # for method in cluster_methods:
    #     db.clustering_results(method)

    # db.create_telemetry_data_table()
    # db.create_race_lap_data()

    ## METHODS FOR QUERYING THE TABLE
    db.query_driver_telemetry


if __name__ == "__main__":
    main()
